const LOCALIDADES_TUCUMAN = [
  "Burruyacu - 7 de Abril",
  "Burruyacu - Benjamin Araoz",
  "Burruyacu - Burruyacu",
  "Burruyacu - El Chanar",
  "Burruyacu - El Naranjo",
  "Burruyacu - Garmendia",
  "Burruyacu - La Ramada de Abajo",
  "Burruyacu - Villa Padre Monti",
  "Capital - San Miguel de Tucuman",
  "Capital - Villa Amalia",
  "Capital - Villa Lujan",
  "Capital - Villa Mariano Moreno",
  "Capital - Villa Munecas",
  "Capital - Villa 9 de Julio",
  "Chicligasta - Alto Verde",
  "Chicligasta - Arcadia",
  "Chicligasta - Concepcion",
  "Chicligasta - Gastona",
  "Chicligasta - La Trinidad",
  "Chicligasta - Medinas",
  "Chicligasta - Monteagudo",
  "Cruz Alta - Alderetes",
  "Cruz Alta - Banda del Rio Sali",
  "Cruz Alta - Colombres",
  "Cruz Alta - Delfin Gallo",
  "Cruz Alta - El Bracho",
  "Cruz Alta - La Florida",
  "Cruz Alta - Las Cejas",
  "Cruz Alta - Los Ralos",
  "Cruz Alta - Ranchillos",
  "Cruz Alta - San Andres",
  "Cruz Alta - San Juan",
  "Famailla - Famailla",
  "Famailla - Ingenio Fronterita",
  "Famailla - Loma Verde",
  "Famailla - Nueva Baviera",
  "Famailla - Santa Lucia",
  "Graneros - Graneros",
  "Graneros - La Madrid",
  "Graneros - Lamadrid",
  "Graneros - Rumi Punco",
  "Graneros - Taco Ralo",
  "Juan Bautista Alberdi - Donato Alvarez",
  "Juan Bautista Alberdi - Escaba",
  "Juan Bautista Alberdi - Juan Bautista Alberdi",
  "Juan Bautista Alberdi - Marapa",
  "Juan Bautista Alberdi - Villa Belgrano",
  "La Cocha - Huasa Pampa",
  "La Cocha - La Cocha",
  "La Cocha - Rumi Punco",
  "La Cocha - San Ignacio",
  "La Cocha - Yanima",
  "Leales - Agua Azul",
  "Leales - Bella Vista",
  "Leales - Estacion Araoz",
  "Leales - Los Gomez",
  "Leales - Los Perez",
  "Leales - Manuel Garcia Fernandez",
  "Leales - Monte Bello",
  "Leales - Quiros",
  "Leales - Rio Colorado",
  "Leales - Santa Rosa de Leales",
  "Leales - Villa de Leales",
  "Lules - El Manantial",
  "Lules - Ingenio San Pablo",
  "Lules - La Reduccion",
  "Lules - Lules",
  "Lules - San Felipe",
  "Monteros - Acheral",
  "Monteros - Amberes",
  "Monteros - Capitan Caceres",
  "Monteros - Monteros",
  "Monteros - Rio Seco",
  "Monteros - Sargento Moya",
  "Monteros - Soldado Maldonado",
  "Rio Chico - Aguilares",
  "Rio Chico - Los Sarmientos",
  "Rio Chico - Rio Chico",
  "Rio Chico - Santa Ana",
  "Rio Chico - Villa Quinteros",
  "Simoca - Atahona",
  "Simoca - Monteagudo",
  "Simoca - Simoca",
  "Simoca - Villa Chicligasta",
  "Simoca - Yerba Buena",
  "Tafi del Valle - Amaicha del Valle",
  "Tafi del Valle - Colalao del Valle",
  "Tafi del Valle - El Mollar",
  "Tafi del Valle - Los Zazos",
  "Tafi del Valle - San Jose",
  "Tafi del Valle - Santa Maria",
  "Tafi del Valle - Tafi del Valle",
  "Tafi Viejo - Cebil Redondo",
  "Tafi Viejo - El Cadillal",
  "Tafi Viejo - Los Nogales",
  "Tafi Viejo - Tafi Viejo",
  "Tafi Viejo - Villa Carmela",
  "Trancas - Choromoro",
  "Trancas - San Pedro de Colalao",
  "Trancas - Trancas",
  "Trancas - Vipos",
  "Trancas - Zarate",
  "Yerba Buena - Cevil Pozo",
  "Yerba Buena - Marcos Paz",
  "Yerba Buena - San Javier",
  "Yerba Buena - Villa Nougues",
  "Yerba Buena - Yerba Buena",
];

module.exports = LOCALIDADES_TUCUMAN;
